import Head from "next/head";
import HomePage from "./home";
import Header from "@/components/Common/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Careerify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Dongle&family=Roboto+Condensed:wght@300&family=Source+Serif+4:ital,wght@1,200&display=swap"
          rel="stylesheet"
        ></link>

        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div>
        <HomePage />
      </div>
    </>
  );
}
